name = "gemini-multilingual-kamus"
compatibility_date = "2024-05-12"

# This tells Wrangler that your site is a static asset project
# and that all the files to be uploaded are in the "dist" directory.
pages_build_output_dir = "dist"