name = "gemini-multilingual-kamus"
compatibility_date = "2024-10-24"
pages_build_output_dir = "dist"

# Local development
[env.development]
# GEMINI_API_KEY will be set via wrangler secret or environment variables